import type { TriageItem } from '@/types';

export const SAMPLE_TRIAGE_ITEMS: TriageItem[] = [
  {
    id: 'triage-reddit-functionalprint',
    sourcePlatform: 'reddit',
    sourceId: 'reddit:t3_functionalprint_001',
    sourceUrl: 'https://www.reddit.com/r/functionalprint/comments/mockdrybox/filament_dry_box_with_desiccant_drawer/',
    canonicalUrl: 'https://www.reddit.com/r/functionalprint/comments/mockdrybox/filament_dry_box_with_desiccant_drawer/',
    title: 'Filament dry box with desiccant drawer',
    description: 'Functional print with a compact dry box design and BOM links in the comments.',
    thumbnailUrl: '',
    contentType: 'model_3d',
    capturedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    ingestedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    status: 'pending',
    aiSummary: 'Likely worth filing into the model catalog because it is a concrete print idea with build context.',
    aiCategories: ['3d-printing', 'functionalprint'],
    aiSuggestedActions: [
      { actionType: 'save_model_catalog', confidence: 0.97, reason: '3D-print content with a likely future build path.', label: 'Save to Model Catalog' },
      { actionType: 'save_karakeep', confidence: 0.71, reason: 'Archive the original discussion and BOM links.', label: 'Save to Karakeep' },
    ],
    aiRelevanceScore: 92,
    aiUrgency: 'evergreen',
    rawMetadata: { subreddit: 'functionalprint' },
    actionsTaken: [],
  },
  {
    id: 'triage-github-homelab',
    sourcePlatform: 'github',
    sourceId: 'github:example/awesome-homelab',
    sourceUrl: 'https://github.com/example/selfhosted-dashboard',
    canonicalUrl: 'https://github.com/example/selfhosted-dashboard',
    title: 'selfhosted-dashboard',
    description: 'A starred repository for dashboards, widgets, and service health rollups.',
    thumbnailUrl: '',
    contentType: 'repo',
    capturedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    ingestedAt: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    status: 'pending',
    aiSummary: 'Strong homelab fit; worth bookmarking and possibly turning into a home-lab plan item.',
    aiCategories: ['github', 'homelab', 'selfhosted'],
    aiSuggestedActions: [
      { actionType: 'save_karakeep', confidence: 0.94, reason: 'GitHub stars map cleanly to long-term bookmarks.', label: 'Save to Karakeep' },
      { actionType: 'create_task_todo', confidence: 0.58, reason: 'Could become a homelab evaluation task.', label: 'Create Todo Task' },
    ],
    aiRelevanceScore: 81,
    aiUrgency: 'trending',
    rawMetadata: { topics: ['selfhosted', 'dashboard'] },
    actionsTaken: [],
  },
  {
    id: 'triage-youtube-rack',
    sourcePlatform: 'youtube',
    sourceId: 'youtube:vid_rack_001',
    sourceUrl: 'https://www.youtube.com/watch?v=mockracklab001',
    canonicalUrl: 'https://www.youtube.com/watch?v=mockracklab001',
    title: 'Building a quiet 10-inch homelab rack',
    description: 'Video walkthrough with product links and rack layout ideas.',
    thumbnailUrl: '',
    contentType: 'video',
    capturedAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    ingestedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    status: 'pending',
    aiSummary: 'Useful research item for the homelab backlog; not urgent, but actionable.',
    aiCategories: ['youtube', 'homelab', 'research'],
    aiSuggestedActions: [
      { actionType: 'create_task_todo', confidence: 0.73, reason: 'Looks like a concrete home-lab plan candidate.', label: 'Create Todo Task' },
      { actionType: 'save_karakeep', confidence: 0.69, reason: 'Preserve source links and notes for later.', label: 'Save to Karakeep' },
    ],
    aiRelevanceScore: 67,
    aiUrgency: 'evergreen',
    rawMetadata: { channel: 'Lab Notes' },
    actionsTaken: [],
  },
  {
    id: 'triage-instagram-print',
    sourcePlatform: 'instagram',
    sourceId: 'instagram:reel_001',
    sourceUrl: 'https://www.instagram.com/reel/C-3dprintidea/',
    canonicalUrl: 'https://www.instagram.com/reel/C-3dprintidea/',
    title: 'Compact cable spool organizer reel',
    description: 'Saved reel showing a compact spool organizer and assembly shots.',
    thumbnailUrl: '',
    contentType: 'video',
    capturedAt: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
    ingestedAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    status: 'snoozed',
    snoozedUntil: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
    aiSummary: 'Potential 3D-print inspiration, but needs manual follow-up because the source is a social reel.',
    aiCategories: ['instagram', '3d-printing', 'inspiration'],
    aiSuggestedActions: [
      { actionType: 'save_model_catalog', confidence: 0.62, reason: 'Possible print idea if a canonical model link can be found.', label: 'Save to Model Catalog' },
      { actionType: 'snooze', confidence: 0.76, reason: 'Best handled when doing a dedicated print-ideas review pass.', label: 'Snooze' },
    ],
    aiRelevanceScore: 54,
    aiUrgency: 'evergreen',
    rawMetadata: { captureMode: 'export-fallback' },
    actionsTaken: [{ actionType: 'snooze', appliedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(), note: 'Review with print ideas tomorrow' }],
  },
];
