import type { ConnectorNotificationTypeDefinition } from './catalog';

export const SYSTEM_NOTIFICATION_TYPES = [
  {
    key: 'morning_start_day',
    label: 'Start your day',
    description: 'A morning summary of planned work and meetings.',
    defaultLevel: 'fyi',
    pushEligible: true,
    pushRecommendation: 'off',
    sensitivity: 'standard',
    defaultPreview: 'title_and_body',
  },
  {
    key: 'triage_nudge',
    label: 'Triage nudge',
    description: 'A reminder that the triage queue needs attention.',
    defaultLevel: 'heads_up',
    pushEligible: true,
    pushRecommendation: 'off',
    sensitivity: 'standard',
    defaultPreview: 'title_and_body',
  },
  {
    key: 'carry_forward',
    label: 'Carry-forward reminder',
    description: 'An end-of-day reminder about unfinished work.',
    defaultLevel: 'heads_up',
    pushEligible: true,
    pushRecommendation: 'off',
    sensitivity: 'standard',
    defaultPreview: 'title_and_body',
  },
  {
    key: 'task_reminder',
    label: 'Task reminder',
    description: 'A reminder explicitly scheduled for a task.',
    defaultLevel: 'heads_up',
    pushEligible: true,
    pushRecommendation: 'action_needed_or_higher',
    sensitivity: 'standard',
    defaultPreview: 'title_and_body',
  },
] as const satisfies readonly ConnectorNotificationTypeDefinition[];

export const GITHUB_NOTIFICATION_TYPES = [
  {
    key: 'pr_review_requested',
    label: 'Pull request review requested',
    description: 'A pull request is waiting for your review.',
    defaultLevel: 'action_needed',
    pushEligible: true,
    pushRecommendation: 'off',
    sensitivity: 'standard',
    defaultPreview: 'title_only',
  },
  {
    key: 'security_alert',
    label: 'Security alert',
    description: 'GitHub reported a repository security alert.',
    defaultLevel: 'urgent',
    pushEligible: true,
    pushRecommendation: 'off',
    sensitivity: 'sensitive',
    defaultPreview: 'title_only',
  },
  {
    key: 'ci_failure',
    label: 'CI failure',
    description: 'A GitHub Actions or check run needs attention.',
    defaultLevel: 'action_needed',
    pushEligible: true,
    pushRecommendation: 'off',
    sensitivity: 'standard',
    defaultPreview: 'title_only',
  },
  {
    key: 'pr_assigned',
    label: 'Pull request assigned',
    description: 'A pull request was assigned to you.',
    defaultLevel: 'action_needed',
    pushEligible: true,
    pushRecommendation: 'off',
    sensitivity: 'standard',
    defaultPreview: 'title_only',
  },
  {
    key: 'issue_assigned',
    label: 'Issue assigned',
    description: 'An issue was assigned to you.',
    defaultLevel: 'action_needed',
    pushEligible: true,
    pushRecommendation: 'off',
    sensitivity: 'standard',
    defaultPreview: 'title_only',
  },
  {
    key: 'mention',
    label: 'Mention',
    description: 'You were mentioned in a GitHub conversation.',
    defaultLevel: 'heads_up',
    pushEligible: true,
    pushRecommendation: 'off',
    sensitivity: 'sensitive',
    defaultPreview: 'title_only',
  },
  {
    key: 'pr_activity',
    label: 'Pull request activity',
    description: 'General activity occurred on a pull request.',
    defaultLevel: 'fyi',
    pushEligible: false,
    pushRecommendation: 'off',
    sensitivity: 'standard',
    defaultPreview: 'title_only',
  },
  {
    key: 'github_activity',
    label: 'GitHub activity',
    description: 'General activity occurred in GitHub.',
    defaultLevel: 'fyi',
    pushEligible: false,
    pushRecommendation: 'off',
    sensitivity: 'standard',
    defaultPreview: 'title_only',
  },
] as const satisfies readonly ConnectorNotificationTypeDefinition[];

export const DOCUMENT_INTELLIGENCE_NOTIFICATION_TYPES = [
  {
    key: 'missing_statement',
    label: 'Missing statement',
    description: 'An expected document statement has not arrived.',
    defaultLevel: 'action_needed',
    pushEligible: true,
    pushRecommendation: 'off',
    sensitivity: 'sensitive',
    defaultPreview: 'title_only',
  },
  {
    key: 'unmatched_eob',
    label: 'Unmatched explanation of benefits',
    description: 'An explanation of benefits needs review.',
    defaultLevel: 'action_needed',
    pushEligible: true,
    pushRecommendation: 'off',
    sensitivity: 'sensitive',
    defaultPreview: 'title_only',
  },
] as const satisfies readonly ConnectorNotificationTypeDefinition[];

export const FINANCE_NOTIFICATION_TYPES = [
  {
    key: 'finance_attribution_review',
    label: 'Finance attribution review',
    description: 'A finance attribution exception needs review.',
    defaultLevel: 'heads_up',
    pushEligible: true,
    pushRecommendation: 'off',
    sensitivity: 'sensitive',
    defaultPreview: 'title_only',
  },
  {
    key: 'finance_insight_recurring_amount_change',
    label: 'Recurring amount increase',
    description: 'A material recurring charge increase was detected.',
    defaultLevel: 'heads_up',
    pushEligible: true,
    pushRecommendation: 'off',
    sensitivity: 'sensitive',
    defaultPreview: 'title_only',
  },
  {
    key: 'finance_insight_large_transaction',
    label: 'Unusually large transaction',
    description: 'An eligible unusually large transaction was detected.',
    defaultLevel: 'action_needed',
    pushEligible: true,
    pushRecommendation: 'action_needed_or_higher',
    sensitivity: 'sensitive',
    defaultPreview: 'title_only',
  },
  {
    key: 'finance_insight_merchant_variance',
    label: 'Merchant spending change',
    description: 'A high-confidence merchant spending change was detected.',
    defaultLevel: 'heads_up',
    pushEligible: true,
    pushRecommendation: 'off',
    sensitivity: 'sensitive',
    defaultPreview: 'title_only',
  },
  {
    key: 'finance_insight_monthly_movers_digest',
    label: 'Monthly spending movers',
    description: 'A grouped digest of high-confidence category and merchant changes.',
    defaultLevel: 'digest',
    pushEligible: true,
    pushRecommendation: 'off',
    sensitivity: 'sensitive',
    defaultPreview: 'title_only',
  },
] as const satisfies readonly ConnectorNotificationTypeDefinition[];

const FINANCE_TEMPLATE_CATALOG_KEYS: Readonly<Record<string, string>> = {
  'finance-attribution-review': 'finance_attribution_review',
  'finance-insight-recurringAmountChange': 'finance_insight_recurring_amount_change',
  'finance-insight-largeTransaction': 'finance_insight_large_transaction',
  'finance-insight-merchantVariance': 'finance_insight_merchant_variance',
  'finance-insight-monthly-movers-digest': 'finance_insight_monthly_movers_digest',
};

export function financeNotificationCatalogKey(templateKey: string): string {
  return FINANCE_TEMPLATE_CATALOG_KEYS[templateKey] ?? templateKey;
}
